### ISSUE TITLE
Add backwards compat support for existing recipe.yml and package.json

### ISSUE THREAD

**Issue by marcoceppi** [ublue-os/yafti#3]
There exists two methods for defining which packages need to be installed after a first boot from main and base. Will need to workshop a method for locating this file in a well known and doing what's expected when that file is loaded

**Comment by EinoHR** [comment]
I'm not 100% sure about this, but I believe `packages.json` was never used to declare flatpaks to install.

And on startingpoint, which is the only non-deprecated repo still using `recipe.yml`, I merged [#13 (feat: use yafti)](https://github.com/ublue-os/startingpoint/pull/13), which adds a "package group" called _Custom_ which is enabled by default and contains all of the flatpaks declared in `recipe.yml`.

As such, it's probably not necessary (and probably even beneficial) for yafti to handle such legacy support.
