### ISSUE TITLE
How do I configure yafti for autorun on boot?

### ISSUE THREAD

**Issue by castrojo** [ublue-os/yafti#57]
This is more a question than an issue. For the old bootscript we had to do this to copy the .desktop file in the right place: 

https://github.com/ublue-os/base/blob/main/etc/profile.d/ublue-firstboot.sh

But afaik yafti doesn't do the touched dotfile thing so what should I be doing here? I've confirmed that everything else about yafti is working on my system other than copying the .desktop file to ~/.config/autostart ...

**Comment by marcoceppi** [comment]
This could still be done. You'd instead check for the desktop file existing

**Comment by marcoceppi** [comment]
That whole copy thing isn't something we can solve directly in this project. It's more a bluefin / ublue / rpm packaging
