### ISSUE TITLE
Partial selections in a submenu don't show in parent checkbox

### ISSUE THREAD

**Issue by castrojo** [ublue-os/yafti#71]
When I go into a section and select a few apps the check boxes show properly for each app, but the parent checkbox isn't selected, so it's hard to tell if the apps are selected for installation.

**Comment by Reidond** [comment]
There is no partial state for switch in Gtk, can i propose that when atleast one package set in group we set enabled state for that group?

**Comment by Reidond** [comment]
Looking thought [Gnome HID](https://developer.gnome.org/hig/patterns/containers/selection-mode.html) it's possible to change switches to checkboxes, i think naturally checkboxes is better for selecting apps to install.

**Comment by marcoceppi** [comment]
this is my problem, there's no partial state for these elements and I haven't found anything that would let me indicate partial selection. Something like this is what I would have expected: https://css-tricks.com/indeterminate-checkboxes/ and maybe it's possible to add this into GTK but it'll require a little more reasearch

**Comment by Reidond** [comment]
> this is my problem, there's no partial state for these elements and I haven't found anything that would let me indicate partial selection. Something like this is what I would have expected: https://css-tricks.com/indeterminate-checkboxes/ and maybe it's possible to add this into GTK but it'll require a little more reasearch

there is [gnome checkboxes](https://developer.gnome.org/hig/patterns/controls/checkboxes.html)
![checkboxes](https://user-images.githubusercontent.com/20406775/235668416-96a191a2-ef1a-47c9-abe8-e61c2922533d.png)

**Comment by marcoceppi** [comment]
Oh, I see - this may work out for us. Thanks for the reference!

**Comment by Arcitec** [comment]
@marcoceppi Or something like this, to alert the user that the group is only partially enabled:

![mockup](https://github.com/ublue-os/yafti/assets/38923130/e9f5797d-7d1b-449f-b177-3efb6998da42)

Would show up anytime something is enabled in the group but not everything.

The "fully checked slider box" would only be "active" when 100% of the items in the group are enabled.

**Comment by abanna** [comment]
going to close this as is already fixed in 0.9.0-beta1
