### ISSUE TITLE
Consider replacing title screen with more direct access to Adw and Gtk components

### ISSUE THREAD

**Issue by marcoceppi** [ublue-os/yafti#8]
Today, title screen is a slim wrapper around Adw.StatusScreen. Other than some basic state manipulation for buttons there isn't much happening. One possibility is to allow more direct access to create Gtk and Adw components instead of needing to proxy them with a class abstraction. For example importing `yafti.screen.adw.StatusScreen` would give you a StatusScreen object with the additional YaftiScreen goodies allow you to map config to component properties. This would only leave Packages as a larger composite component and allow greater flexibility in definition of screens

**Comment by abanna** [comment]
Gonna close this one.  feel like the new layout addresses original concern.
