### ISSUE TITLE
Group "user data" files in subfolders

### ISSUE THREAD

**Issue by Arcitec** [ublue-os/yafti#98]
Currently we use `~/.config/yafti-last-run`.

Best practices is to create sub-folders, as such:

`~/.config/yafti/last-run` and `~/.local/share/yafti` and `~/.cache/yafti` etc.

Especially important if we decide to grow the amount of files we have per-user.

**Comment by marcoceppi** [comment]
This is configurable in the yafti yaml configuration. I'll open a PR to update the default value

**Comment by Arcitec** [comment]
@marcoceppi Ah, that's excellent news. Is that the only file Yafti creates in user home directories?

Also, since this is Python, you can leverage this technique:

```py
from pathlib import Path

config_file = Path.home() / ".config/yafti/last-run.yml"
if not config_file.parent.is_dir():
    config_file.mkdir(mode=0o755, parents=True, exist_ok=True)
```

**Comment by marcoceppi** [comment]
It is the only file today, yes. If you'd like to submit a PR go for it. Otherwise I'll adjust later this week

**Comment by Arcitec** [comment]
@marcoceppi It was pretty easy to figure out the code. Nice job with the structure. :)

PR: https://github.com/ublue-os/yafti/pull/102
